"""empty message

Revision ID: 08000d22d695
Revises: 542cf4ac3665
Create Date: 2026-02-12 17:50:54.399963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08000d22d695'
down_revision = '542cf4ac3665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('products_user_id_key'), type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('products_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
